lang: fr-FR
title: Tuto JB QGIS
plugins:
  - jekyll-remote-theme
remote_theme: benbalter/retlab

contact_links:
  - name: Twitter
    url: https://twitter.com/jbdesbas
    icon: twitter

nav_pages:
  - contact.md
