lang: fr-FR
title: Tuto JB QGIS
plugins:
  - jekyll-remote-theme
remote_theme: benbalter/retlab

baseurl: "/tuto-qgis"

contact_links:
  - name: Twitter
    url: https://twitter.com/jbdesbas
    icon: twitter

nav_pages:
  - contact.md

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
